### ISSUE TITLE
Forecaster: do it properly

### ISSUE THREAD

**Issue by alphaville** [GPUEngineering/RapidNet#12]
How the forecaster show work:

The class `Forecaster` should serve as a _abstraction_ to allow for the implementation of different types of Forecasters. We can have:

- `FileForecaster`: Forecaster from File where the forecasts (nominal predictions of prices and demands) are read from a JSON file (pretty much what is done now)
- `ArimaForecaster`: Which implements an ARIMA model
- `SvmForecaster`: Which implements an SVM model
- Any other possible forecaster than the end-user might want to implement by subclassing the base class `Forecaster`.

The base class should be very simple and define certain abstract methods which need to be implemented by the derived classes. These can be:

```.cpp
/**
 * Predicts water demands and prices (simultaneously) and 
 * provides the predictions in a common vector.
 * @param predicted predicted values
 * @return status code (0 if the prediction was successful)
 */
int predict(real_t* predicted);
```

or, if it is more convenient, implement two separate methods:

```.cpp
int predictDemand(real_t* predictedDemand);
int predictPrices(real_t* predictedPrices);
```

**Comment by alphaville** [comment]
This is not resolved. `Forecaster` should become an abstract class and have different implementations. One of those should be a `FileForecaster` which reads the forecasts from a file.

**Comment by alphaville** [comment]
I unassigned this issue from all milestones. We can do it later, but it needs to be resolved at some point.

**Comment by ajaykumarsampath** [comment]
I used the keyword `virtual` and made the `fileForecast` as the default option.  We can modify or updated in the derived class which can be `svmForecaster` or `arimaForecaster`. I guess there is a way to integrate `svmModel` as the libsvm has a `c` implementation. But I would like to leave it for later. 
 
Regarding the calculation of `L` and `Lhat` by using the function you have suggested, it need those lapacke.h and blas libraries in the server. So I have some troubles in proceeding forward. I have to communicate with Lenardo to install them. 

Recently, I modified the constructor structure that use the `controlConfig.json` file to build the `smpcController`. I have to rewrite to suit this modification. But now with the

**Comment by alphaville** [comment]
Currently there is no separation of functionality: The `Forecaster` class should contain only what is necessary and be an `abstract` class: it should have no constructors, it should not definite private fields such as `pathToNominalDemand` and so on. Then, there should be a **subclass** of `Forecaster` which predicts by reading the predictions from a file. There can be more implementations and the end-user should be able to implement their own forecasters by subclassing this class. 

Anyway, this is not first priority now - we can do a nice refactoring a bit later.
