### ISSUE TITLE
Makefile

### ISSUE THREAD

**Issue by alphaville** [GPUEngineering/RapidNet#17]
We need a `Makefile` as well as detailed installation instructions.

**Comment by alphaville** [comment]
@ajaykumarsampath Ajay, I think the [makefile](https://github.com/GPUEngineering/RapidNet/blob/master/src/makefile) you added is not an actual makefile. Can you test it from the command line? That makefile seems to depend on [several other files](https://github.com/GPUEngineering/RapidNet/blob/master/src/makefile#L10) (with extension `.mk`) which are auto-generated. The main makefile should be named `Makefile` (with uppercase M).

**Comment by ajaykumarsampath** [comment]
I know this problem. I just closed this issue as we duplicated in #32
