### ISSUE TITLE
Add getters in the class

### ISSUE THREAD

**Issue by ajaykumarsampath** [GPUEngineering/RapidNet#2]
Remove friend functions and add getter's for all the required
private variables in all the classes 
 - DwnNetwork 
   - All the variables in the system 
 - Forecaster 
    - All the variables corresponding to the scenario tree 
 - Engine 
   - Factor step matrices 
 - SmpcController 
    - For the control actions

**Comment by alphaville** [comment]
We may easily address this issue. We now have the method

```.cpp
void controllerSmpc();
```

We need a method to return the control action (just u_0). I would propose that we make `controllerSmpc()` into a private method and implement the following:


```.cpp
int controllerSmpc(real_t * controlAction);
```

This returns a status code and uses the pointer `controlAction` to store the control action data.

We need another method to write the control action into a JSON file, but we can do that later.
