### ISSUE TITLE
Renaming the files 

### ISSUE THREAD

**Issue by ajaykumarsampath** [GPUEngineering/RapidNet#3]
All names follow the camel case format 
 renaming the
- `DWNnetwork` to `DwnNetwork`
- `SMPController`  to `SmpcController`
- `ClassNameHeader.cuh` to ` ClassName.cuh`

**Comment by alphaville** [comment]
We need to rename `cudaKernelHeader.cuh`. Filenames should start with an uppercase letter. I would propose `Utilities.cuh` or something like that.
