### ISSUE TITLE
SmpcController construction (configuration)

### ISSUE THREAD

**Issue by alphaville** [GPUEngineering/RapidNet#5]
The SMPC controller should be constructed using the following information:

- The DWN network information
- A forecaster
- A controller configuration which contains all necessary parameters, weights, etc which are associated with the controller configuration

![smpccontrollerconcept](https://cloud.githubusercontent.com/assets/125415/24215562/7a83d35c-0f39-11e7-9275-3aee9f38e1ae.png)

A possible template for the constructor of SmpcController is the following:

```.cpp
SmpcController(
    string network,
    string scenarioTree,
    string controllerConfiguration){
 this->engine = new Engine(network, scenarioTree);
 /* parse the data provided in controllerConfiguration */
 this->penaltyStateX = ...;
}
```

**Comment by alphaville** [comment]
I updated the diagram: `Forecaster` should not link to `ScenarioTree`. The reason is that `SmpcController` will link to (i) `Forecaster` and (ii) `Engine`. It is absolutely necessary that the Engine has access to the scenario tree structure and values, so `Engine` has to link to `ScenarioTree`.

**Comment by alphaville** [comment]
@ajaykumarsampath Note that the ER diagram has been updated. The latest version is [here](https://github.com/ajaykumarsampath/DwnController/wiki).

**Comment by ajaykumarsampath** [comment]
The ER diagram in the final version. 
[smpcControllerConcept_2.pdf](https://github.com/GPUEngineering/RapidNet/files/1245077/smpcControllerConcept_2.pdf)
